export const theme = {
  main: "sith",
  fontSizes: [12, 14, 16, 20, 24, 32],
  colors: {
    primary: "#27fcfa",
    secondary: "#6e25c8",
    tertiary: "#4514a7",
    dark: "#24212a",
    "text-light": "#9692ad",
    textDark: "#24212a",
    light: "#ffffff",
    success: "",
    error: "",
    darnger: "",
    warning: "",
    info: "",
    default: "#FFFFFF",
  },
  spacing: {
    xs: "0",
    sm: "4",
    md: "8",
    lg: "16",
    xl: "16",
    xxl: "32",
  },
  fonts: ["Nunito", "sans-serif"],
  screen: {
    xs: 0,
    sm: "35rem",
    md: "45rem",
    lg: "55rem",
    xl: "75rem",
    xxl: "80rem",
  },
  container: {
    sm: "75rem",
    md: "70rem",
    lg: "65rem",
    xl: "60rem",
    xxl: "80rem",
  },
  skew: {
    xs: "0deg",
    sm: "2deg",
    md: "4deg",
    lg: "8deg",
    xl: "15deg",
    xxl: "15deg",
  },
};
